In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/hotel-reservations-classification-dataset/Hotel Reservations.csv

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [7]:
data=pd.read_csv('/kaggle/input/hotel-reservations-classification-dataset/Hotel Reservations.csv')

In [28]:
df=data.copy()

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            36275 non-null  object
 1   no_of_adults                          36275 non-null  int64
 2   no_of_children                        36275 non-null  int64
 3   no_of_weekend_nights                  36275 non-null  int64
 4   no_of_week_nights                     36275 non-null  int64
 5   type_of_meal_plan                     36275 non-null  object
 6   required_car_parking_space            36275 non-null  int64
 7   room_type_reserved                    36275 non-null  object
 8   lead_time                             36275 non-null  int64
 9   arrival_year                          36275 non-null  int64
 10  arrival_month                         36275 non-null  int64
 11  arrival_date                          36275 non-null  int64
 12  market_segment_type                   36275 non-null  object
 13  repeated_guest                        36275 non-null  int64
 14  no_of_previous_cancellations          36275 non-null  int64
 15  no_of_previous_bookings_not_canceled  36275 non-null  int64
 16  avg_price_per_room                    36275 non-null  float64
 17  no_of_special_requests                36275 non-null  int64
 18  booking_status                        36275 non-null  object
dtypes: float64(1), int64(13), object(5)
memory usage: 5.3+ MB

In [12]:
df.describe()

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests
count,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000
mean,1.844962,0.105279,0.810724,2.204300,0.030986,85.232557,2017.820427,7.423653,15.596995,0.025637,0.023349,0.153411,103.423539,0.619655
std,0.518715,0.402648,0.870644,1.410905,0.173281,85.930817,0.383836,3.069894,8.740447,0.158053,0.368331,1.754171,35.089424,0.786236
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2017.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,1.000000,0.000000,17.000000,2018.000000,5.000000,8.000000,0.000000,0.000000,0.000000,80.300000,0.000000
50%,2.000000,0.000000,1.000000,2.000000,0.000000,57.000000,2018.000000,8.000000,16.000000,0.000000,0.000000,0.000000,99.450000,0.000000
75%,2.000000,0.000000,2.000000,3.000000,0.000000,126.000000,2018.000000,10.000000,23.000000,0.000000,0.000000,0.000000,120.000000,1.000000
max,4.000000,10.000000,7.000000,17.000000,1.000000,443.000000,2018.000000,12.000000,31.000000,1.000000,13.000000,58.000000,540.000000,5.000000

In [13]:
df.isnull().sum()

Booking_ID                              0
no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
booking_status                          0
dtype: int64

In [17]:
df.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled

In [25]:
for col in df:
    print(col+':')
    print(df[col].unique())

Booking_ID:
['INN00001' 'INN00002' 'INN00003' ... 'INN36273' 'INN36274' 'INN36275']
no_of_adults:
[2 1 3 0 4]
no_of_children:
[ 0  2  1  3 10  9]
no_of_weekend_nights:
[1 2 0 4 3 6 5 7]
no_of_week_nights:
[ 2  3  1  4  5  0 10  6 11  7 15  9 13  8 14 12 17 16]
type_of_meal_plan:
['Meal Plan 1' 'Not Selected' 'Meal Plan 2' 'Meal Plan 3']
required_car_parking_space:
[0 1]
room_type_reserved:
['Room_Type 1' 'Room_Type 4' 'Room_Type 2' 'Room_Type 6' 'Room_Type 5'
 'Room_Type 7' 'Room_Type 3']
lead_time:
[224   5   1 211  48 346  34  83 121  44   0  35  30  95  47 256  99  12
 122   2  37 130  60  56   3 107  72  23 289 247 186  64  96  41  55 146
  32  57   7 124 169   6  51  13 100 139 117  39  86  19 192 179  26  74
 143 177  18 267 155  46 128  20  40 196 188  17 110  68  73  92 171 134
 320 118 189  16  24   8  10 182 116 123 105 443 317 286 148  14  85  25
  28  80  11 162  82  27 245 266 112  88  69 273   4  97  31  62 197 280
 185 160 104  22 292 109 126 303  81  54  15 161 147  87 127 418 156  58
 433 111 195 119  59  78 335 103  70  76 144  49  77  36  79  21  33 164
 152  43 102  71 209  93  53 302 239  45 167 113  84   9 166 174  61 151
  52  67 282  38 175  89 133  65  66  50 159 386 115 237 125  91  29 221
 213 198  75 180 236 120 230  63 136 309 157 268 217  94 305  98  42 154
 330 137 184 232 304 114 257 265 191 101 259 149 170 271 207 108 210 222
 296 194 145 153 275 158 301 349 200 315 181 263 176 141 270 150 359 244
 219 142 138 276 178 163 377 290 216 226 258 254 193 131 208 215 190 381
 231 248 106 308 140 173 168 172  90 249 205 129 212 135 220 277 253 132
 183 255 223 336 288 229 319 199 203 228 246 235 294 281 202 361 287 291
 313 206 269 279 261 214 274 250 187 240 241 323 322 227 225 233 338 283
 327 204 352 165 251 299 314 285 238 328 278 332 243 201 307 272 252 242
 284 297 324 260 262 326 295 218 234 353 300 355 306 298 331 341 318 333
 372 311 310 345 264 325 293 348 350 351]
arrival_year:
[2017 2018]
arrival_month:
[10 11  2  5  4  9 12  7  6  8  3  1]
arrival_date:
[ 2  6 28 20 11 13 15 26 18 30  5 10  4 25 22 21 19 17  7  9 27  1 29 16
  3 24 14 31 23  8 12]
market_segment_type:
['Offline' 'Online' 'Corporate' 'Aviation' 'Complementary']
repeated_guest:
[0 1]
no_of_previous_cancellations:
[ 0  3  1  2 11  4  5 13  6]
no_of_previous_bookings_not_canceled:
[ 0  5  1  3  4 12 19  2 15 17  7 20 16 50 13  6 14 34 18  8 10 23 11 49
 47 53  9 33 22 24 52 21 48 28 39 25 31 38 26 51 42 37 35 56 44 27 32 55
 45 30 57 46 54 43 58 41 29 40 36]
avg_price_per_room:
[ 65.   106.68  60.   ... 118.43 137.25 167.8 ]
no_of_special_requests:
[0 1 3 2 4 5]
booking_status:
['Not_Canceled' 'Canceled']

In [30]:
from sklearn.preprocessing import LabelEncoder

In [32]:
le=LabelEncoder()

In [34]:
df_col=['type_of_meal_plan','room_type_reserved','market_segment_type','booking_status']

In [38]:
for i in df_col:
    df[i]=le.fit_transform(df[i])

In [40]:
df.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,0,0,0,224,2017,10,2,3,0,0,0,65.00,0,1
1,INN00002,2,0,2,3,3,0,0,5,2018,11,6,4,0,0,0,106.68,1,1
2,INN00003,1,0,2,1,0,0,0,1,2018,2,28,4,0,0,0,60.00,0,0
3,INN00004,2,0,0,2,0,0,0,211,2018,5,20,4,0,0,0,100.00,0,0
4,INN00005,2,0,1,1,3,0,0,48,2018,4,11,4,0,0,0,94.50,0,0

In [44]:
for col in df:
    print(col+':')
    print(df[col].unique())

Booking_ID:
['INN00001' 'INN00002' 'INN00003' ... 'INN36273' 'INN36274' 'INN36275']
no_of_adults:
[2 1 3 0 4]
no_of_children:
[ 0  2  1  3 10  9]
no_of_weekend_nights:
[1 2 0 4 3 6 5 7]
no_of_week_nights:
[ 2  3  1  4  5  0 10  6 11  7 15  9 13  8 14 12 17 16]
type_of_meal_plan:
[0 3 1 2]
required_car_parking_space:
[0 1]
room_type_reserved:
[0 3 1 5 4 6 2]
lead_time:
[224   5   1 211  48 346  34  83 121  44   0  35  30  95  47 256  99  12
 122   2  37 130  60  56   3 107  72  23 289 247 186  64  96  41  55 146
  32  57   7 124 169   6  51  13 100 139 117  39  86  19 192 179  26  74
 143 177  18 267 155  46 128  20  40 196 188  17 110  68  73  92 171 134
 320 118 189  16  24   8  10 182 116 123 105 443 317 286 148  14  85  25
  28  80  11 162  82  27 245 266 112  88  69 273   4  97  31  62 197 280
 185 160 104  22 292 109 126 303  81  54  15 161 147  87 127 418 156  58
 433 111 195 119  59  78 335 103  70  76 144  49  77  36  79  21  33 164
 152  43 102  71 209  93  53 302 239  45 167 113  84   9 166 174  61 151
  52  67 282  38 175  89 133  65  66  50 159 386 115 237 125  91  29 221
 213 198  75 180 236 120 230  63 136 309 157 268 217  94 305  98  42 154
 330 137 184 232 304 114 257 265 191 101 259 149 170 271 207 108 210 222
 296 194 145 153 275 158 301 349 200 315 181 263 176 141 270 150 359 244
 219 142 138 276 178 163 377 290 216 226 258 254 193 131 208 215 190 381
 231 248 106 308 140 173 168 172  90 249 205 129 212 135 220 277 253 132
 183 255 223 336 288 229 319 199 203 228 246 235 294 281 202 361 287 291
 313 206 269 279 261 214 274 250 187 240 241 323 322 227 225 233 338 283
 327 204 352 165 251 299 314 285 238 328 278 332 243 201 307 272 252 242
 284 297 324 260 262 326 295 218 234 353 300 355 306 298 331 341 318 333
 372 311 310 345 264 325 293 348 350 351]
arrival_year:
[2017 2018]
arrival_month:
[10 11  2  5  4  9 12  7  6  8  3  1]
arrival_date:
[ 2  6 28 20 11 13 15 26 18 30  5 10  4 25 22 21 19 17  7  9 27  1 29 16
  3 24 14 31 23  8 12]
market_segment_type:
[3 4 2 0 1]
repeated_guest:
[0 1]
no_of_previous_cancellations:
[ 0  3  1  2 11  4  5 13  6]
no_of_previous_bookings_not_canceled:
[ 0  5  1  3  4 12 19  2 15 17  7 20 16 50 13  6 14 34 18  8 10 23 11 49
 47 53  9 33 22 24 52 21 48 28 39 25 31 38 26 51 42 37 35 56 44 27 32 55
 45 30 57 46 54 43 58 41 29 40 36]
avg_price_per_room:
[ 65.   106.68  60.   ... 118.43 137.25 167.8 ]
no_of_special_requests:
[0 1 3 2 4 5]
booking_status:
[1 0]

In [47]:
df2=df.copy()

In [48]:
df2.drop(['Booking_ID','arrival_date'],axis=1,inplace=True)

In [51]:
x=df2.iloc[:,:16]

In [53]:
x.head()

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests
0,2,0,1,2,0,0,0,224,2017,10,3,0,0,0,65.00,0
1,2,0,2,3,3,0,0,5,2018,11,4,0,0,0,106.68,1
2,1,0,2,1,0,0,0,1,2018,2,4,0,0,0,60.00,0
3,2,0,0,2,0,0,0,211,2018,5,4,0,0,0,100.00,0
4,2,0,1,1,3,0,0,48,2018,4,4,0,0,0,94.50,0

In [75]:
y=df2.iloc[:,-1:]

In [76]:
y.head()

   booking_status
0               1
1               1
2               0
3               0
4               0

In [71]:
from sklearn.model_selection import train_test_split

In [77]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [63]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((29020, 16), (29020, 1), (7255, 16), (7255, 1))

In [65]:
from sklearn.ensemble import RandomForestClassifier

In [137]:
rfc=RandomForestClassifier(n_estimators=50,max_depth=15)

In [138]:
model=rfc.fit(x_train,y_train.values.ravel())

In [140]:
y_pred=rfc.predict(x_test)

In [129]:
from sklearn.metrics import accuracy_score

In [141]:
accuracy_score(y_test,y_pred)

0.8920744314266024